# Syncs the shared GOOGLE_MAPS_API_KEY from repo-root .env into
# ios/Flutter/Secrets.xcconfig for Xcode / flutter build ios.
# Android continues to read .env via Gradle — this script does not touch Android.

$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$envPath = Join-Path $repoRoot '.env'
$outPath = Join-Path $repoRoot 'ios\Flutter\Secrets.xcconfig'

if (-not (Test-Path $envPath)) {
    Write-Error "Missing .env at $envPath. Create it with GOOGLE_MAPS_API_KEY=..."
}

$key = ''
Get-Content $envPath | ForEach-Object {
    $line = $_.Trim()
    if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith('#')) {
        return
    }
    $sep = $line.IndexOf('=')
    if ($sep -le 0) {
        return
    }
    $name = $line.Substring(0, $sep).Trim()
    if ($name -eq 'GOOGLE_MAPS_API_KEY') {
        $key = $line.Substring($sep + 1).Trim()
    }
}

if ([string]::IsNullOrWhiteSpace($key)) {
    Write-Error 'GOOGLE_MAPS_API_KEY not found in .env'
}

@"
// Generated by tools/sync_ios_maps_key.ps1 — do not commit.
// Same key as Android (GOOGLE_MAPS_API_KEY from .env).
GOOGLE_MAPS_API_KEY=$key
"@ | Set-Content -Path $outPath -Encoding utf8

Write-Host "Wrote $outPath"
